name: Bump version
on:
  push:
    branches:
      - emanuelbrea-patch-1
jobs:
  build:   
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v3
        with:  
          fetch-depth: 0  
      - name: Bump version and push tag
        id: version
        uses: juliansangillo/tag-version@v1.5
        with:
          production-branch: main
          test-branch: emanuelbrea-patch-1
          dev-branch: develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}          
